#!/bin/bash

# delete existing 'ip6tables-generated.rules' file
rm -f /etc/iptables/ip6tables-generated.rules

# store current date/time
genDateTime=`date -u +"%Y-%m-%d at %H:%M:%S UTC"`

# build full 'ip6tables-generated.rules' file
touch /etc/iptables/ip6tables-generated.rules
echo "# rules generated by ip6tables-helper.sh on ${genDateTime}" > /etc/iptables/ip6tables-generated.rules
for filter6rulefile in /etc/iptables/ip6tables.d/filter/*.rules; do
	cat "$filter6rulefile" >> /etc/iptables/ip6tables-generated.rules
	echo -ne "\n" >> /etc/iptables/ip6tables-generated.rules
done
