#!/bin/bash

# delete existing 'iptables-generated.rules' file
rm -f /etc/iptables/iptables-generated.rules

# store current date/time
genDateTime=`date -u +"%Y-%m-%d at %H:%M:%S UTC"`

# build full 'iptables-generated.rules' file
touch /etc/iptables/iptables-generated.rules
echo "# rules generated by iptables-helper.sh on ${genDateTime}" > /etc/iptables/iptables-generated.rules
for filterrulefile in /etc/iptables/iptables.d/filter/*.rules; do
	cat "$filterrulefile" >> /etc/iptables/iptables-generated.rules
	echo -ne "\n" >> /etc/iptables/iptables-generated.rules
done
